// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFZoqRwNtq_ZfLRVFBO8Y5HMGbjU3b-nw',
    appId: '1:254944106441:web:91a400d01b19e46aaaba18',
    messagingSenderId: '254944106441',
    projectId: 'my-easy-tutorial-campaign',
    authDomain: 'my-easy-tutorial-campaign.firebaseapp.com',
    storageBucket: 'my-easy-tutorial-campaign.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3pZdZHblOGkKY_RpzRCvWg9lxwJQnY4k',
    appId: '1:254944106441:android:3f1ac38b612f3235aaba18',
    messagingSenderId: '254944106441',
    projectId: 'my-easy-tutorial-campaign',
    storageBucket: 'my-easy-tutorial-campaign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRNUZ9PJzikz72SCCpqs3X0AkYtRZ8XNI',
    appId: '1:254944106441:ios:381b51dfba587257aaba18',
    messagingSenderId: '254944106441',
    projectId: 'my-easy-tutorial-campaign',
    storageBucket: 'my-easy-tutorial-campaign.appspot.com',
    iosClientId: '254944106441-dtjofl9qrerjob8eq10l09tj5kv4cgf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSampleCampaign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRNUZ9PJzikz72SCCpqs3X0AkYtRZ8XNI',
    appId: '1:254944106441:ios:381b51dfba587257aaba18',
    messagingSenderId: '254944106441',
    projectId: 'my-easy-tutorial-campaign',
    storageBucket: 'my-easy-tutorial-campaign.appspot.com',
    iosClientId: '254944106441-dtjofl9qrerjob8eq10l09tj5kv4cgf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSampleCampaign',
  );
}
